name: Ajiroba Test Result

on:
  push:
    branches:
      - main
    paths:
      - 'postman-tests/**'

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman and Allure Reporter
        run: |
          npm install -g newman newman-reporter-allure

      - name: Install Java (required for Allure CLI)
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre-headless

      - name: Download and Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -xzf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Run Postman Collection with Allure Reporter
        run: |
          newman run "postman-tests/Ajiroba.postman_collection.json" \
            -e "postman-tests/Ajiroba_postman_environment.json" \
            -r cli,allure --reporter-allure-export=allure-results

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
